name: Lint and Test

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: "latest"
    - name: Create lock file
      run: uv lock
    - name: Install dependencies
      run: |
        uv sync --dev --locked
    - name: Verify installation
      run: |
        uv run python --version
        uv run black --version
        uv run flake8 --version
        uv run pytest --version
    - name: Run Black formatting check
      run: |
        uv run black --check --diff .
    - name: Run flake8 linting
      run: |
        uv run flake8 . --show-source --statistics
    - name: Run tests
      run: |
        uv run pytest tests/ --maxfail=5 --disable-warnings -v
